settings:
    path: ''
    defaults:
        _controller: \Mindy\Bundle\SettingBundle\Controller\Admin\SettingsController::list

settings_form:
    path: /{slug}
    defaults:
        _controller: \Mindy\Bundle\SettingBundle\Controller\Admin\SettingsController::settings
    requirements:
        slug: '[a-zA-Z0-9-\_]+'
