services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Mindy\Template\Library\LibraryInterface:
            public: true
            tags: ['template.library']

    Mindy\Bundle\SettingBundle\:
        resource: '../../*'
        exclude: '../../{Tests,vendor}'

    Mindy\Bundle\SettingBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Mindy\Bundle\SettingBundle\Settings\SettingsManager:
        public: true
